name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Copy LICENSE file
        run: cp -p LICENSE mmd_uuunyaa_tools/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: artifact
          path: mmd_uuunyaa_tools/
          if-no-files-found: error
